### ISSUE TITLE
Avoid chunk transfer for dictionary attacks

### ISSUE THREAD

**Issue by FSzopen** [hsc-lab/octopus#1]
Slavenodes should have their dictionaries in memory so that they don't need big chunks to be transfered.

**Comment by Moloson** [comment]
Is it really necessary ? I mean, when you change the chunk size, program will
 re-transfer them all without deleting the old ones. In some case it could fill
-up the disk in case of large dictionaries. Except if you always use the same number of nodes and the same dictionaries, I don't think the benefit is that good.

**Comment by FSzopen** [comment]
Hi,

That is not the way I thought about it. When they are started, slavenodes should be able to choose between downloading dictionaries they don't have yet in memory and not downloading them. Then the masternode will send dictionary chunks only if slavenodes need it. Of course that would be a benefit only if slavenodes use same dictionaries. But if they do not, that would not change anything for them as they could choose not to download dictionaries.

Elsewhere I am afraid that I do not understand why the number of nodes should always be the same...

**Comment by FSzopen** [comment]
Issue has been resolved. I close it, feel free to re-open it if you have any suggestion regarding my last commits!
